version: "3"
services:
  app:
    container_name: fastify-app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gooonzick/fastify-app
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - ./app:/root/home/app

  caddy:
    image: caddy:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
