version: "3"
services:
  db:
    image: postgres
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      POSTGRES_PASSWORD: password

  app:
    container_name: fastify-app
    build:
      context: .
      dockerfile: Dockerfile
    image: fastify-app
    ports:
      - "8080:8080"
    command: npm test
    depends_on:
      - db
