version: "3"
services:
  app:
    container_name: fastify-app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gooonzick/fastify-app
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - /app:/root/home/app
