version: "3"
services:
  db:
    image: postgres
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

  app:
    container_name: fastify-app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gooonzick/fastify-app
    ports:
      - "8080:8080"
    command: npm start
    volumes:
      - ./app:/root/home/app
    depends_on:
      - db

  caddy:
    image: caddy:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
