version: "3"
services:
  app:
    image: gooonzick/fastify-app
    container_name: fastify-app
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
